# Generated by Django 4.2.11 on 2024-04-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id_news', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=100)),
                ('rate', models.IntegerField()),
                ('author', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('comm_count', models.IntegerField()),
            ],
        ),
    ]
