# Generated by Django 4.2.11 on 2024-04-15 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id_comment', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('id_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.news')),
                ('id_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.comment')),
            ],
        ),
    ]
