# Generated by Django 4.2.11 on 2024-04-15 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.comment'),
        ),
    ]
